// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbSkE-PP5860BVoCNMVQDCSR0BTIKmV0',
    appId: '1:766419188981:web:d0718e03674ae389d319bc',
    messagingSenderId: '766419188981',
    projectId: 'ogrencibilgisistemi-daa51',
    authDomain: 'ogrencibilgisistemi-daa51.firebaseapp.com',
    storageBucket: 'ogrencibilgisistemi-daa51.appspot.com',
    measurementId: 'G-TQ3P5NBX01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBYvBrOaYDzpRQrXATli8BIlX0gARGzU',
    appId: '1:766419188981:android:b740b6fa4ddd0ff3d319bc',
    messagingSenderId: '766419188981',
    projectId: 'ogrencibilgisistemi-daa51',
    storageBucket: 'ogrencibilgisistemi-daa51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs7ZKfF64tVoy_rHGhTzK0jR0OdlwstrM',
    appId: '1:766419188981:ios:bc6e843644eeff8fd319bc',
    messagingSenderId: '766419188981',
    projectId: 'ogrencibilgisistemi-daa51',
    storageBucket: 'ogrencibilgisistemi-daa51.appspot.com',
    iosClientId: '766419188981-aips8t2ran5nnubnb5aflg2b13u8flb2.apps.googleusercontent.com',
    iosBundleId: 'com.atak.apps.obs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs7ZKfF64tVoy_rHGhTzK0jR0OdlwstrM',
    appId: '1:766419188981:ios:bc6e843644eeff8fd319bc',
    messagingSenderId: '766419188981',
    projectId: 'ogrencibilgisistemi-daa51',
    storageBucket: 'ogrencibilgisistemi-daa51.appspot.com',
    iosClientId: '766419188981-aips8t2ran5nnubnb5aflg2b13u8flb2.apps.googleusercontent.com',
    iosBundleId: 'com.atak.apps.obs',
  );
}
